//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpRDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee201file
    {
        public int EmployeeId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Middlename { get; set; }
        public string Suffix { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string Birthdate { get; set; }
        public Nullable<int> Age { get; set; }
        public string Department { get; set; }
        public byte[] ProfileImg { get; set; }
        public string ImagePath { get; set; }
    }
}
